# Generated by Django 5.2.8 on 2025-11-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('answer_1', models.CharField(max_length=255, verbose_name='Answer to Q1: z-coordinate of point P')),
                ('answer_2', models.CharField(max_length=255, verbose_name='Answer to Q2: Possible values for k (comma-separated)')),
                ('answer_3', models.CharField(max_length=255, verbose_name='Answer to Q3: Coordinates of the midpoint of RT (x, y)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
