# Generated by Django 5.2.8 on 2025-11-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='answer_1',
            field=models.CharField(max_length=255, verbose_name='Answer to Q1: Midpoint Coordinates (x, y)'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='answer_2',
            field=models.CharField(max_length=255, verbose_name='Answer to Q2: Distance'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='answer_3',
            field=models.CharField(max_length=255, verbose_name='Answer to Q3: Distance Squared'),
        ),
    ]
